name: Test Action

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sha="$(gh api /repos/${{github.repository}}/contents/README -q .sha)"
        gh api -X PUT /repos/${{github.repository}}/contents/README -f message=update -f content="$(date | base64)" -f sha="$sha"
    - uses: actions/checkout@v3
      with:
        repository: ${{github.action_repository}}
        ref: ${{github.action_ref}}
        path: .tmp/test-repo-2
    - shell: bash
      run: ls .tmp/test-repo-2
    - uses: ./.tmp/test-repo-2/other
