name: Test Action

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        ls
        env
    - shell: bash
      run: |
        sha="$(gh api /repos/${{github.repository}}/contents/README -q .sha)"
        gh api -X PUT /repos/${{github.repository}}/contents/README -f message=update -f content="$(date | base64)" -f sha="$sha"
    - uses: ${{github.action_repository}}/other@${{github.action_ref}}
